### ISSUE TITLE
Unable to uninstall the app after first install

### ISSUE THREAD

**Issue by mannp** [Secure-File-Manager/Secure-File-Manager#27] opened 2021-04-21 16:32 UTC
I installed the app via fdroid and did some basic config.

Closed the app and went to uninstall.

The app crashes my package manager and I  am unable to uninstall your app.

I don't have any encrypted files or folders and have tried clearing my data and removing, which did not work either.

Any thoughts on how I may now remove it please?

No issues uninstalling other apps.

I don't have root.

Many thanks in advance

**Comment by Alfavio** [comment] 2021-04-22 13:23
Hi @mannp. I tried to reproduce your issue on several devices. I tried to uninstall the app installed from Google Play and also F-Droid. In both cases, the app was uninstalled successfully. Please, can you upload a video to reproduce your problem and also your device model?

**Comment by mannp** [comment] 2021-04-22 16:46
Hi @Alfavio 

Firstly, thanks for creating what looks to be becoming a great app :) 

Second, I have investigated further and something odd is happening.

I use an Mi 8 pro with paranoid android 5 installed, but I am not sure that is the root cause.

I found that the app seems to have the same 'id' or whatever the name is between the play store and f-droid version, which I have not seen before.

So the problem comes for me when installing the f-droid version and trying to uninstall with f-droid, it just won't remove it.

If i go into the play store, it sees the app installed and I can successfully uninstall it through the play store...

With other apps I find only the store that installed the app can remove it, but that may not be the case 100% of the time.

Lastly, I wondered with your security approach whether utilising my gnupg key somehow in the app would be possible? To derive the key you use on the app perhaps? So that i could decrypt my files with my existing key....

**Comment by Alfavio** [comment] 2021-04-23 07:33
@mannp 

> Firstly, thanks for creating what looks to be becoming a great app :)

Thank you, I appreciate it :heart: 

> I use an Mi 8 pro with paranoid android 5 installed, but I am not sure that is the root cause.

This is strange, the app supports minimal Android 8 _(API level 26)_. It should not be possible to install the application on older device.

> I found that the app seems to have the same 'id' or whatever the name is between the play store and f-droid version, which I have not seen before.

This should be normal. Which apps have different applicationId in the Play Store and F-droid?

> Lastly, I wondered with your security approach whether utilising my gnupg key somehow in the app would be possible? To derive the key you use on the app perhaps? So that i could decrypt my files with my existing key....

The app uses keys from the Android Keystore. More information about encrypting files is in the [FAQ](https://github.com/Secure-File-Manager/Secure-File-Manager/wiki/Frequently-Asked-Questions#how-are-my-files-encrypted). The app currently doesn't support PGP keys. :confused:  I created new [issue](https://github.com/Secure-File-Manager/Secure-File-Manager/issues/30) for that. Maybe in the future support for PGP will be added.

**Comment by mannp** [comment] 2021-04-23 09:27
> This is strange, the app supports minimal Android 8 (API level 26). It should not be possible to install the application on older device.

Its running android 10 ... ?

> This should be normal. Which apps have different applicationId in the Play Store and F-droid?

I thought a good number, but perhaps I am wrong there I have not had chance to check further.

> The app uses keys from the Android Keystore. More information about encrypting files is in the FAQ. The app currently doesn't support PGP keys. confused I created new issue for that. Maybe in the future support for PGP will be added.

Okay thanks for creating an issue for pgp keys, I will keep an eye on the project for future, thanks again.

**Comment by Alfavio** [comment] 2021-04-23 09:50
> Its running android 10 ... ?

Yes, Android 8+.

Anyway, it's weird that you couldn't uninstall the app, but it seems your issue was resolved. I can't reproduce this issue. I'm closing this issue now, if more users will report the same issue, I will look at it closer.

**Closed by Alfavio** 2021-04-23 09:50 UTC
Labels: bug
