### ISSUE TITLE
Selecting multiple folders to unhide deletes the hidden files and does not unhide them

### ISSUE THREAD

**Issue by JM2707** [Secure-File-Manager/Secure-File-Manager#25] opened 2021-04-20 16:10 UTC
This happened while an unhide was in progress, and the files are neither in the hidden tab or in the normal filesystem.

**Comment by Alfavio** [comment] 2021-04-20 16:28
Hi @JM2707. Thank you for the bug report. Please, can you describe your issue in more detail? I tried to hide/unhide multiple folders _(which contain sub-folders a sub-files)_ and it work correctly.

**Comment by JM2707** [comment] 2021-04-20 17:19
Of course.

- There were 10 folders with multiple files inside but not subfolders on the root of the hidden files tab.
- I long-pressed a folder and clicked the unhide button. It asked me where to unhide them and when I pressed ok, it started to unhide it.
- As it had some files inside, it didn't finish instantly. While it was still unhiding that folder, I selected the remaining 9 and unselected the one that was unhiding.
- I clicked the unhide button again, and when I accepted, those 9 folders disappeared in the hidden tab and in the unhide location there only was the first folder I unhided with all its files and the 9 remaining folders, but empty.

Those files are gone, because I had 9 gb free before trying to unhide them and now I have 11.

**Comment by Alfavio** [comment] 2021-04-22 14:11
Thank you @JM2707, this detailed description helped me to find the bug. I fixed it and release a new version [0.1.6](https://github.com/Secure-File-Manager/Secure-File-Manager/releases/tag/v0.1.6-beta). The new version will be soon available at Google Play and F-Droid. Please, let me know the issue is resolved on your device after you install the new version. I hope this bug did not affected you much :confused:

**Comment by Alfavio** [comment] 2021-06-02 15:29
No answer, so I close this issue and I consider it as solved.

**Closed by Alfavio** 2021-06-02 15:29 UTC
Labels: bug
