### ISSUE TITLE
SD card issue

### ISSUE THREAD

**Issue by User1l0** [Secure-File-Manager/Secure-File-Manager#1] opened 2021-02-24 23:05 UTC

**Comment by Alfavio** [comment] 2021-02-25 06:39
Hi @User1l0. Thank you for the bug report and feature request! I appreciate that. Please, can you describe to me better what did you mean with "_Please fix the SD card storage access framework access problem"_? Can you please describe more information about the bug and how to reproduce it? For the dark theme, I created separated issue #4, but now it has low priority. The pattern is not secure, because it has low security by design. Because of that, I don't plan to add this feature.

**Comment by User1l0** [comment] 2021-02-25 09:27
>I don't plan to add this feature.

Then how do i suppose to encrypt and modify my files in SD Card with secure file manager? it has no sd access ☹️

**Comment by Alfavio** [comment] 2021-02-25 11:59
I meant that use pattern as auth I don't plan to add. Support for SD cards is already in the app. I tested it and the SD card works correctly on my device. OTG devices are not currently supported.

**Comment by Alfavio** [comment] 2021-02-25 13:40
You are correct, I tried copy file to SD card and also encrypt file in the SD card and it is not working. I will fix it at soon as possible.

**Comment by Alfavio** [comment] 2021-02-26 15:25
It should be fixed in the new release. The new version will be soon available at Google Play and F-Droid. I had to disable the encryption, decryption, and Zip functionality for the SD cards.  Copy, move and rename operations should work now correctly. Thank you @User1l0 for reporting the bug. Please, let me know if the SD card works correctly on your device after you install the new version.

_Background note: [`EncryptedFile`](https://developer.android.com/reference/androidx/security/crypto/EncryptedFile) and [`ZipFile`](https://javadoc.io/static/net.lingala.zip4j/zip4j/2.6.1/net/lingala/zip4j/ZipFile.html) don't support [`DocumentFile`](https://developer.android.com/reference/androidx/documentfile/provider/DocumentFile)_, which the app uses to access SD cards.

**Comment by fux0r2009** [comment] 2021-03-01 12:58
@Alfavio please make sure it's Black AMOLED Theme not the grayish dark thanks :)

**Closed** 2021-03-09 14:53 UTC
Labels: bug
