### ISSUE TITLE
Unable to decrypt files - Pixel devices

### ISSUE THREAD

**Issue by Rufusdotrufus** [Secure-File-Manager/Secure-File-Manager#49] opened 2021-05-22 06:15 UTC
Downloaded ver. 0.1.8 Beta on two different devices (Pixel 3 Android 12, Pixel 2 Graphene Os) via f-droid.  Loaded app on both devices and used different functions, including encrypting and zipping test files  Everything worked as expected.  

Few hours later, decided to unzip and decrypt the files from earlier tests.  Logged into app.  App was completely unresponsive with the exception of being able to open settings menu.  Went to other phone, logged on and app was unresponsive as well.

**Comment by Rufusdotrufus** [comment] 2021-05-22 22:53
Well...today is a new day. :)  App opened normally on both of my devices today.  I am able to browse all folders as expected.  Neither of my phones were shut down nor was the app killed and restarted on either device.  Who knows the cause of the glitch that occurred on both of my devices yesterday????

Although....new issue cropped up, on both devices.  Locked files did not unlock cleanly.  While decrypting, the following error occurred:  java.io.IOException no matching key in the cypher stream.

I continued to lock and unlock files repeatedly.  The above occurs in roughly 50% of my tests.

**Comment by Alfavio** [comment] 2021-06-02 15:51
Hi @Rufusdotrufus. Thank you for the bug report.  I tried to reproduce your issue, but unsuccessful. Maybe this issue is related to Graphene OS, but I don't own a Pixel device, so I can't test it. :confused: Please, try to reinstall the app.

**Comment by Rufusdotrufus** [comment] 2021-06-02 19:50
Hi @Alfavio .  Just to be clear, I am also experiencing this bug on a vanilla Pixel 3 fully updated.  I would love to include screen shots of the error messages and what is happening but despite toggling screen shot block on and off, the app completely blocks screenshots.

As per your suggestion, I deleted the app and reinstalled.  Still experiencing the same issue with the app unable to decrypt encrypted files.  There is definitely something amiss.  

Good luck with your app...it is a much needed foss app.

**Comment by Alfavio** [comment] 2021-06-03 06:57
@Rufusdotrufus 

> I would love to include screen shots of the error messages and what is happening but despite toggling screen shot block on and off, the app completely blocks screenshots.

Please, try restarting the app after enabling screenshots.

> As per your suggestion, I deleted the app and reinstalled. Still experiencing the same issue with the app unable to decrypt encrypted files. There is definitely something amiss.

I looked deeper into this issue. I noticed, that the app uses an alpha version of library [androidx.security.crypto ](https://developer.android.com/reference/androidx/security/crypto/package-summary) witch is responsible for encrypting/decrypting files. I tried to revert this library to a stable version in the [feature/cryptoStableVersion](https://github.com/Secure-File-Manager/Secure-File-Manager/tree/feature/cryptoStableVersion) branch. Please, can you try this version on your device?

[secure-file-manager-debug.zip](https://github.com/Secure-File-Manager/Secure-File-Manager/files/6589574/secure-file-manager-debug.zip)

> Good luck with your app...it is a much needed foss app.

Thank you! :heart:

**Comment by Rufusdotrufus** [comment] 2021-06-03 20:49
@Alfavio   Downloaded the zip and installed the version of the app you had enclosed.

#1 Reliability of encrypting/decrypting is greatly improved.

#2 There is still an issue that crops up.

First image shows file I tested to encrypt.

![1](https://user-images.githubusercontent.com/81439737/120709025-31c0ce80-c471-11eb-8938-3f7c4f607a89.png)

Second image shows file successfully encrypted.

![2](https://user-images.githubusercontent.com/81439737/120709162-5cab2280-c471-11eb-9b5e-2c9df4784a81.png)

Third image shows an error message while trying to decrypt

![3](https://user-images.githubusercontent.com/81439737/120709249-73ea1000-c471-11eb-9253-1c09dc62e32d.png)

Fourth image shows the file in 2 different states - still encrypted after the generated error message & the file actually decrypted.

![4](https://user-images.githubusercontent.com/81439737/120709416-adbb1680-c471-11eb-9522-7ead1c939c5c.png)

Note: the decrypted file opens despite the error message

I don't have a lot of time at the moment to run a sequence of tests but when I get the chance I will see what I can do as far as how often the above error gets thrown during decryption.

**Comment by HardcoreSuperstar** [comment] 2021-06-23 19:03
Hello, I have exact same issue. 
I installed the latest version released here from master and worked well. 
It was encrypting normal an decrypting al  files. 
But then I installed several apps from PlayMarket, and error start to rising
java.io.IOException: No matching key found for ciphertext in the stream

The error above have also too for some image files.
And mine happen for text files

**Comment by Alfavio** [comment] 2022-08-02 15:53
I tried this bug on the physical device _(Pixel 6 with Graphene Os)_ and I can't reproduce the issue. I'm closing the issue for now. If somebody will have the same issue with detailed steps to reproduce, I will reopen the issue.

**Closed by Alfavio** 2022-08-02 15:53 UTC
Labels: bug
